name: OneTask
description: "App di gestione progetti e team"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  path: ^1.9.0
  sqflite: ^2.3.3+1
  sqflite_common_ffi: any
  table_calendar: ^3.1.1   
  google_fonts: ^6.2.1   
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#C1BDB2"
  image: assets/splash.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "./android/app/src/main/res/drawable-mdpi/splash.png"
